# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97ae484e1fa7a1e7fe87a751e7c1ecb05d52d5b8976bdf5c47671eb3a38c4a784d48779a0204e26a1fd2412cc96f38078bfc165bf428f8f35578f0f2d0fd012e

test:
  secret_key_base: 87cf23bd9cdbb6bda4a75f84deeb1e4a5ea942eca1fdaa06e82b69f61ecf4d1847c6f030b2354d76cc5d2405b38c65df7ffc9668ec225c0a6e19e0a176c651db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
